---
title: "Class14"
author: "Megan Hayes"
date: "February 27, 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("DESeq2")
```

```{r}
biocLite("DESeq2")
```

```{r}
counts <- read.csv("data/airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <-  read.csv("data/airway_metadata.csv", stringsAsFactors = FALSE)
```

```{r}
nrow(counts)
```

```{r}
all(metadata$id == colnames(counts)[-1])
```

```{r}
# find the column names (ids) of the 'control' exps
control.ids <- metadata$id[metadata[,"dex"] =="control"]
head(counts[,control.ids])
control <- counts[,control.ids]
rownames(control) <- counts$ensgene
head(control)
```


```{r}
# find the column names (ids) of the 'treated' exps
treated.ids <- metadata$id[metadata[,"dex"] == "treated"]
treated <- counts[,treated.ids]
rownames(treated) <- counts$ensgene
head(treated)
```

```{r}
## control means
control.mean <- rowSums(control)/ncol(control)
head(control.mean)
```

```{r}
## treated means
treated.mean <- rowMeans(treated)
head(treated.mean)
```

```{r}
## combine treated and control means
meancounts <- data.frame(control.mean, treated.mean)
colSums(meancounts)
```

```{r}
## plot meancounts
plot(meancounts$control.mean, meancounts$treated.mean, log = "xy")
```

```{r}
##log-log plot (adjust axis)
meancounts$log2fc <- log2(meancounts[,"treated.mean"]/meancounts[,"control.mean"])
head(meancounts)
```

```{r}
#we need to filter ou the zero value entry genes
zero.vals <- which(meancounts[,1:2]==0, arr.ind=TRUE)
head(zero.vals)

to.rm <- unique(zero.vals[,1])
#unique -> zeros don't get counted twice
mycounts <- meancounts[-to.rm,]
##-to.rm -> everything but meancount[-to.rm]
head(mycounts)
```

```{r}
#how many genes above a designated threshold (in this case, log2fc +-2)
up.ind <- mycounts$log2fc > 2
down.ind <- mycounts$log2fc < (-2)
sum(up.ind)
sum(down.ind)
```

```{r}
anno <- read.csv("annotables_grch38.csv")
```

```{r}
head(anno)
dim(anno)
```

```{r}
head(mycounts)
```


```{r}
##using the merge() function to add the annotation data to our mycounts results

mycounts.anno <- merge(x=mycounts, y=anno, by.x="row.names", by.y = "ensgene")
head(mycounts.anno)

```

```{r}
##nsource("http://bioconductor.org/biocLite.R")
biocLite("AnnotationDbi")
biocLite("org.Hs.eg.db")
```

```{r}
library("AnnotationDbi")
library("org.Hs.eg.db")
```

```{r}
columns(org.Hs.eg.db)
```

```{r}
mycounts$symbol <- mapIds(org.Hs.eg.db,
                     keys=row.names(mycounts),
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
head(mycounts)
```

```{r}
library(DESeq2)
citation("DESeq2")
```

```{r}
## build or DESeqDataSet
dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds
```

```{r}
dds <- DESeq(dds)
```

```{r}
## get our results
res <- results(dds)
summary(res, alpha=0.01)

```

```{r}
plot(res$log2FoldChange, -log(res$padj))
```

```{r}
mycols <- rep("gray", nrow(res))
mycols[abs(res$log2FoldChange) > 2] = "red"
subset.inds <- res$padj < 0.01 & abs(res$log2FoldChange) > 2
mycols[subset.inds] <- "blue"

plot(res$log2FoldChange, -log(res$padj), col=mycols)
```

